const categories = [
  "Hindu Temple",
  "Professional Sports Team",
  "Artist",
  "Digital creator",
  "Film Director",
  "Architectural Designer",
  "Sports & Fitness Instruction",
  "Arts & entertainment",
  "Photographer",
  "Reel creator",
  "Community",
  "Editor",
  "Legal",
  "Musician/band",
  "Politician",
  "Beauty, cosmetic & personal care",
  "Entrepreneur",
  "Comedian",
  "Wedding Planning Service",
  "Public figure",
  "Song",
  "Blogger",
  "Education",
  "Actor",
  "Fashion Model",
  "E-commerce website",
  "Shopping & retail",
  "Dancer",
  "Agriculture",
  "Hotel resort",
  "Sports",
  "Musician",
  "Home Improvement",
  "Personal blog",
  "Science, Technology & Engineering",
  "Art",
  "Advertising/Marketing",
  "Sports team",
  "Local & travel website",
  "Political Organization",
  "Media/news company",
  "Gamer",
  "Product/service",
  "Food & Drink",
  "Writer",
  "Jewelry/watches",
  "Baby & children's clothing store",
  "Pet Breeder",
  "Fashion Designer",
  "Cinematographer",
  "Skin Care Service",
  "Restaurant",
  "Finance",
  "Book",
  "Footwear store",
  "Real Estate",
  "Health Food Store",
  "Motivational speaker",
  "Financial service",
  "Athlete",
  "Discount Store",
  "Model",
  "Doctor",
  "Diving Spot",
  "Clothing (Brand)",
  "Mobile Phone Shop",
  "Health/beauty",
  "Vacation Home Rental",
  "Music video",
  "Carpenter",
  "Interior Design Studio",
  "Armed Forces",
  "Brand",
  "Baby goods/kids goods",
  "Just for fun",
  "Lawyer & Law Firm",
  "Comedy club",
  "Party Entertainment Service",
  "Automotive, Aircraft & Boat",
  "Creative Director",
  "Fan page",
  "Astrologist",
  "Religious organization",
  "Nonprofit organization",
  "Furniture",
  "Podcast",
  "Women's clothing store",
  "Home decor",
  "Clothing store",
  "Science Website",
  "Hair Salon",
  "Beauty Salon",
  "Kitchen/cooking",
  "Scientist",
  "Event Planner",
  "Social Service",
  "Fashion Stylist",
  "Choreographer",
  "Gardener",
  "Dance Studio",
  "Political Party",
  "Real Estate Developer",
  "Fitness Trainer",
  "Singer",
  "Dessert Shop",
  "Marketing Agency",
  "Internet Marketing Service",
  "Media",
  "Travel Company",
  "Sportswear Store",
  "Sports & recreation",
  "Cafe",
  "Music Producer",
  "Journalist",
  "TV show",
  "Cars",
  "Gaming video creator",
  "Employment Agency",
  "Photography Videography",
  "News & media website",
  "Entertainment website",
  "Astrologist & Psychic",
  "Health & wellness website",
  "Interest",
  "Animals & Pets",
  "Author",
  "Bakery"
]

export default categories